name: Update Pinterest Archive

on:
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install Pinterest CLI
        run: |
          go install github.com/tamnd/pinterest-cli/cmd/pin@latest

      - name: Test Pinterest
        run: |
          pin board pins "https://www.pinterest.com/Shamsowl/think-about-it/" -o jsonl
